force-app/main/default/objects/Advertising__c/Advertising__c.object-meta.xml
<CustomObject>
    <label>Advertising</label>
    <nameField>
        <label>Advertising Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Advertising</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Basket__c/Basket__c.object-meta.xml
<CustomObject>
    <label>Basket</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Basket Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Baskets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Basket__c/fields/Commodity__c.field-meta.xml
<CustomField>
    <fullName>Commodity__c</fullName>
    <label>Commodity</label>
    <referenceTo>Commodity__c</referenceTo>
    <relationshipLabel>Baskets</relationshipLabel>
    <relationshipName>Baskets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Basket__c/fields/Count__c.field-meta.xml
<CustomField>
    <fullName>Count__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Count</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Category__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Animals</fullName>
            </value>
            <value>
                <fullName>Art</fullName>
            </value>
            <value>
                <fullName>Clothes</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Furniture</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Category__c/fields/CountCommodity__c.field-meta.xml
<CustomField>
    <fullName>CountCommodity__c</fullName>
    <label>CountCommodity</label>
    <summaryForeignKey>Commodity__c.Category__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Comment__c/Comment__c.object-meta.xml
<CustomObject>
    <label>Comment</label>
    <nameField>
        <displayFormat>C-{00000}</displayFormat>
        <label>Comment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Comment__c/fields/Commodity__c.field-meta.xml
<CustomField>
    <fullName>Commodity__c</fullName>
    <label>Commodity</label>
    <referenceTo>Commodity__c</referenceTo>
    <relationshipLabel>Comments</relationshipLabel>
    <relationshipName>Comments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Comment__c/fields/Mark__c.field-meta.xml
<CustomField>
    <fullName>Mark__c</fullName>
    <label>Mark</label>
    <precision>1</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Commodity__c/Commodity__c.object-meta.xml
<CustomObject>
    <label>Commodity</label>
    <nameField>
        <label>Commodity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Commodities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Commodity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Commodities</relationshipLabel>
    <relationshipName>Commodities</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Commodity__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <referenceTo>Category__c</referenceTo>
    <relationshipLabel>Commodities</relationshipLabel>
    <relationshipName>Commodities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Commodity__c/fields/Count__c.field-meta.xml
<CustomField>
    <fullName>Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Count</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Commodity__c/fields/CountComment__c.field-meta.xml
<CustomField>
    <fullName>CountComment__c</fullName>
    <label>CountComment</label>
    <summaryForeignKey>Comment__c.Commodity__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Commodity__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <formula>if(CountComment__c = 0, 0, SumCommentMarks__c /  CountComment__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rating</label>
    <precision>18</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Delivery__c/Delivery__c.object-meta.xml
<CustomObject>
    <label>Delivery</label>
    <nameField>
        <displayFormat>D-{00000}</displayFormat>
        <label>Delivery Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deliveies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <summarizedField>DeliveryItem__c.Price__c</summarizedField>
    <summaryForeignKey>DeliveryItem__c.Delivery__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Created</fullName>
                <default>true</default>
                <label>Created</label>
            </value>
            <value>
                <fullName>Taken</fullName>
            </value>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Done</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/DeliveryItem__c/DeliveryItem__c.object-meta.xml
<CustomObject>
    <label>Delivery Item</label>
    <nameField>
        <displayFormat>DI-{00000}</displayFormat>
        <label>DeliveryItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DeliveryItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DeliveryItem__c/fields/Commodity__c.field-meta.xml
<CustomField>
    <fullName>Commodity__c</fullName>
    <label>Commodity</label>
    <referenceTo>Commodity__c</referenceTo>
    <relationshipLabel>Delivery Items</relationshipLabel>
    <relationshipName>Delivery_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DeliveryItem__c/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <label>Delivery</label>
    <referenceTo>Delivery__c</referenceTo>
    <relationshipLabel>Delivery Items</relationshipLabel>
    <relationshipName>Delivery_Items</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Favorite__c/Favorite__c.object-meta.xml
<CustomObject>
    <label>Favorite</label>
    <nameField>
        <label>Favorite Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Favorites</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Favorite__c/fields/Commodity__c.field-meta.xml
<CustomField>
    <fullName>Commodity__c</fullName>
    <label>Commodity</label>
    <referenceTo>Commodity__c</referenceTo>
    <relationshipLabel>Favorites</relationshipLabel>
    <relationshipName>Favorites</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ShopController.cls
/**
 * Created by odubavets on 04.01.2022.
 */

public with sharing class ShopController {

    @AuraEnabled (cacheable=true)
    public static List<Category__c> getCategory() {
        return [
                SELECT Name, Category__c, CountCommodity__c
                FROM Category__c
                WHERE CountCommodity__c != 0
                ORDER BY Category__c, Name
        ];
    }

    @AuraEnabled (cacheable=true)
    public static List<Commodity__c> getCommodities(Id categoryId) {
        String query = 'SELECT Id, Name, Image__c, Price__c, Description__c, Account__r.Name, CountComment__c,\n' +
                            'Count__c, Rating__c, Account__c, Active__c, Approved__c\n' +
                        'FROM Commodity__c\n' +
                        'WHERE Active__c = true AND Approved__c = true';
        if (categoryId != null) query += ' AND Category__c = \'' + categoryId + '\'';
        query += ' ORDER BY Name';
        if (categoryId == null) query += ' LIMIT 50';
        return Database.query(query);
    }

    @AuraEnabled (cacheable=true)
    public static List<Advertising__c> getAdvertising() {
        return [
                SELECT Id, Image__c, Name
                FROM Advertising__c
        ];
    }

    @AuraEnabled (cacheable=true)
    public static List<Basket__c> getBasket() {
        return [
                SELECT Id, Commodity__r.Name, Count__c, Commodity__r.Price__c, Commodity__r.Image__c,
                        Commodity__r.Count__c, Commodity__r.Active__c, Commodity__r.Approved__c
                FROM Basket__c
        ];
    }

    @AuraEnabled (cacheable=true)
    public static List<Comment__c> getComments(Id commodityId) {
        return [
                SELECT Description__c, Mark__c
                FROM Comment__c
                WHERE Commodity__c = :commodityId
        ];
    }

    @AuraEnabled (cacheable=true)
    public static List<Commodity__c> getCommoditiesByAccount(Id accountId) {
        return [
                SELECT Id, Name, Image__c, Price__c, Description__c, Account__r.Name, CountComment__c, Count__c, Rating__c, Account__c
                FROM Commodity__c
                WHERE Active__c = true AND Approved__c = true AND Account__c = :accountId
                ORDER BY Name
        ];
    }

    @AuraEnabled
    public static void clearBasket(List<Basket__c> basketItems) {
        delete basketItems;
    }

    private static List<Commodity__c> updateCommodities(List<Basket__c> basketItems) {
        Boolean updateParam = true;
        List<Commodity__c> commodities = new List<Commodity__c>();
        List<ID> commodityIds = new List<ID>();
        for (Basket__c basketItem : basketItems) {
            commodityIds.add(basketItem.Commodity__c);
        }
        List<Commodity__c> aCommodities = [
                SELECT Count__c, Approved__c, Active__c
                FROM Commodity__c
                WHERE Id IN :commodityIds
                FOR UPDATE
        ];
        for (Basket__c basketItem : basketItems) {
            if (updateParam == false) break;
            for (Commodity__c aCommodity : aCommodities) {
                if (basketItem.Commodity__c == aCommodity.Id) {
                    if (aCommodity.Count__c >= basketItem.Count__c
                            && aCommodity.Approved__c == true
                            && aCommodity.Active__c == true) {
                        aCommodity.Count__c -= basketItem.Count__c;
                        commodities.add(aCommodity);
                    } else {
                        updateParam = false;
                        Approval.unlock(commodities, false);
                    }
                    break;
                }
            }
        }
        return updateParam ? commodities : null;
    }

    @AuraEnabled
    public static void orderBasket(List<Basket__c> basketItems, Object info) {
        List<Commodity__c> commodities = updateCommodities(basketItems);
        if (commodities != null) {
            Delivery__c aDelivery = new Delivery__c(Status__c = 'Created');
            insert aDelivery;
            List<DeliveryItem__c> deliveryItems = new List<DeliveryItem__c>();
            for (Basket__c aBasketItem : basketItems) {
                deliveryItems.add(new DeliveryItem__c(
                        Commodity__c = aBasketItem.Commodity__c,
                        Price__c = aBasketItem.Commodity__r.Price__c * aBasketItem.Count__c,
                        Count__c = aBasketItem.Count__c,
                        Delivery__c = aDelivery.Id
                ));
            }
            insert deliveryItems;
            update commodities;
            clearBasket(basketItems);
        }
    }

    @AuraEnabled
    public static void addToBasket(Id commodityId) {
        Basket__c aBasket = new Basket__c(Commodity__c = commodityId, Count__c = 1);
        insert aBasket;
    }

    @AuraEnabled (cacheable=true)
    public static Boolean checkInBasket(Id commodityId) {
        return [SELECT COUNT() FROM Basket__c WHERE Commodity__c = :commodityId] == 0 ? false : true;
    }

    @AuraEnabled
    public static Comment__c addComment(Id commodityId, String comment, Integer mark) {
        Comment__c aComment = new Comment__c(Commodity__c = commodityId, Description__c = comment, Mark__c = mark);
        insert aComment;
        return aComment;
    }

    @AuraEnabled
    public static void deleteFromBasket(Basket__c basketItem) {
        delete basketItem;
    }

    @AuraEnabled (cacheable=true)
    public static Boolean checkCommentByAccountAndCommodity(Id commodityId) {
        return [SELECT COUNT() FROM Comment__c WHERE Commodity__c = :commodityId] == 0 ? true : false;
    }

    @AuraEnabled (cacheable=true)
    public static List<Delivery__c> getOrders() {
        return [
                SELECT Id, Status__c, FORMAT(CreatedDate) formattedDate, Price__c, (select Commodity__r.Name, Count__c, Price__c, Id from Delivery_Items__r)
                FROM Delivery__c
                ORDER BY CreatedDate DESC
        ];
    }

    @AuraEnabled (cacheable=true)
    public static Boolean getFavoriteByCommodity(Id commodityId) {
        return [SELECT COUNT() FROM Favorite__c WHERE Commodity__c = :commodityId] == 0 ? true : false;
    }

    @AuraEnabled
    public static void changeFavorite(Id commodityId) {
        List<Favorite__c> favorites = [SELECT Id FROM Favorite__c WHERE Commodity__c = :commodityId];
        if (favorites.isEmpty()) {
            Favorite__c aFavorite = new Favorite__c(Commodity__c = commodityId);
            insert aFavorite;
        } else {
            delete favorites;
        }
    }

    @AuraEnabled (cacheable=true)
    public static List<Commodity__c> getFavorite() {
        return [
                SELECT Id, Name, Image__c, Price__c, Description__c, Account__r.Name, CountComment__c, Count__c, Rating__c, Account__c, Active__c, Approved__c
                FROM Commodity__c
                WHERE Id IN (SELECT Commodity__c FROM Favorite__c)
                ORDER BY Name
        ];
    }

    @AuraEnabled (cacheable=true)
    public static List<Commodity__c> getByFilter(Decimal minPrice, Decimal maxPrice, String inStock, Integer rating, Id categoryId) {
        String query = 'SELECT Id, Name, Image__c, Price__c, Description__c, Account__r.Name, CountComment__c, Count__c, ' +
                            'Rating__c, Account__c, Active__c, Approved__c\n' +
                        'FROM Commodity__c\n' +
                        'WHERE Active__c = true and Approved__c = true\n' +
                            'AND Price__c >= ' + minPrice +
                            'AND Price__c <= ' + maxPrice +
                            'AND Rating__c >= ' + rating;
        if (inStock == 'InStock') {
            query += ' AND Count__c > 0';
        }
        if (categoryId != null) {
            query += ' AND Category__c = \'' + categoryId + '\'';
        }
        query += ' ORDER BY Name';
        return Database.query(query);
    }

    @AuraEnabled (cacheable=true)
    public static Decimal getMaxPrice() {
        return (Decimal) [SELECT MAX(Price__c) FROM Commodity__c][0].get('expr0');
    }

}